name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: migrate 
      run: php artisan migrate
    - name: install package
      run: composer update
    - name: Optimize
      run: php artisan optimize:clear
