name: main-actions
run-name: ${{ github.actor }} is running GitHub Actions
on:
  push:
    branches: [ "main",]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6   # This will auto run the command composer install by default
      with:
        php_version: '7.4'
        version: '2.3.5'
        # command: composer install   # If you want a custom composer install, write here
    - name: Run API Test
      run: php artisan test
