name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Migrate
      run: php artisan migrate
      working-directory: /var/www/html/saveorder

    - name: Install package
      run: composer update
      working-directory: /var/www/html/saveorder

    - name: Optimize
      run: php artisan optimize:clear
      working-directory: /var/www/html/saveorder
